/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CompanyInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProjectType = IDL.Variant({
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'projectType' : ProjectType,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Service = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
  'getContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ProjectType],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CompanyInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProjectType = IDL.Variant({
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'projectType' : ProjectType,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Service = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  
  return IDL.Service({
    'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
    'getContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ProjectType],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };