/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyInfo {
  'name' : string,
  'email' : string,
  'website' : string,
  'address' : string,
  'phone' : string,
}
export interface ContactFormSubmission {
  'projectType' : ProjectType,
  'name' : string,
  'message' : string,
  'phone' : string,
}
export type ProjectType = { 'commercial' : null } |
  { 'residential' : null };
export interface Service { 'name' : string, 'description' : string }
export interface _SERVICE {
  'getCompanyInfo' : ActorMethod<[], CompanyInfo>,
  'getContactFormSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, ProjectType],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];